### ISSUE TITLE
`sshkey` customization is ignored

### ISSUE THREAD

**Issue by supakeen** [osbuild/image-builder-cli#142]
The [documented](https://osbuild.org/docs/user-guide/blueprint-reference/#ssh-keys) `sshkey` customization is not plumbed through in `images`. The struct exists but nothing seems to be generated on it. 

```console
$ cat sshkey.toml 
[[customizations.sshkey]]
user = "testuser"
key = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKNh/u8oWHfYwr01X8G8ijSC3hPfKfLpK8MISxg2mq1O user@muja.home.arpa"
$ ./image-builder manifest --distro fedora-43 --blueprint sshkey.toml minimal-raw-zst | jq . | rg testuser     
$
```

**Comment by supakeen** [comment]
A workaround is to use the `directories` and `files` customization like so:

```toml
[[customizations.directories]]
path = "/home/testuser/.ssh"
mode = "0700"

[[customizations.files]]
path = "/home/testuser/.ssh/authorized_keys"
mode = "0600"
data = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKNh/u8oWHfYwr01X8G8ijSC3hPfKfLpK8MISxg2mq1O user@muja.home.arpa"
```

**Comment by supakeen** [comment]
@FrostyX, after a chat with @achilleas-k (see the linked PR) it turns out that the correct way to do this is by using the `user` customization instead. It's not written down super clearly in the documentation but it will modify a user if it already exists. Something like:

```toml
[[customizations.user]]
name = "testuser"
keys = ["ssh-edsa XXXX xxx"]
```

Is thus the way SSH keys could be added to users.

**Comment by FrostyX** [comment]
Thank you both. I will test once I can and reopen if necessary.

**Comment by FrostyX** [comment]
> [[customizations.user]]
> name = "testuser"
> keys = ["ssh-edsa XXXX xxx"]

I don't think this works. Maybe I am looking in a wrong place, but `~/.ssh` wasn't created for my user.

**Comment by supakeen** [comment]
I've reopened the issue and I'll take a look tomorrow then. Is the blueprint the one from your repository?

**Comment by supakeen** [comment]
Oh, I see what I did. I mixed the `sshkeys` and `users` customizations. The `users` customization takes a single key as a string:

```toml
[[customizations.users]]
name = "testuser"
key = "ssh-edsa XXXX xxx"
```
